version: 2.1
workflows:
  version: 2
  unit_and_integration_tests:
    jobs:
      - unit
      - integration
jobs:
  unit:
    docker:
      - image: circleci/node:11.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - ~/.yarn
            - ~/.cache
            - node_modules
          key: v1-1-dependencies-{{ checksum "package.json" }}

      - run: yarn test:unit --maxWorkers=2
  integration:
    docker:
      - image: circleci/node:11.6-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - ~/.yarn
            - ~/.cache
            - node_modules
          key: v1-1-dependencies-{{ checksum "package.json" }}

      - run: yarn test:e2e --headless